import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { LabelBadge } from "./LabelBadge.js";

export interface VerdictMeta {
  markdown: string;
  model?: string;
  provider?: string;
  stub: boolean;
}

interface Props {
  verdict: VerdictMeta;
}

function shortAddr(addr: string): string {
  if (addr.length <= 14) return addr;
  return `${addr.slice(0, 8)}…${addr.slice(-4)}`;
}

export function VerdictPanel({ verdict }: Props) {
  const { markdown, model, provider, stub } = verdict;
  return (
    <section className="p-5 rounded-lg border border-slate-700 bg-slate-900/50">
      <header className="flex items-center justify-between gap-2 pb-3 border-b border-slate-800">
        <div>
          <h2 className="text-xs uppercase tracking-wider text-slate-500">
            Verdict
          </h2>
          {model && (
            <p className="mt-1 text-[10px] font-mono text-slate-500">
              {model}
              {provider && provider !== "stub" && (
                <span className="ml-2 text-slate-600">
                  via {shortAddr(provider)}
                </span>
              )}
            </p>
          )}
        </div>
        <LabelBadge label={stub ? "EMULATED" : "ESTIMATED"} />
      </header>
      <div className="mt-3 text-sm leading-relaxed text-slate-200 prose prose-invert prose-sm max-w-none">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
      </div>
      <p className="mt-3 text-[10px] text-slate-500">
        {stub
          ? "Verdict synthesis short-circuited to a deterministic stub. Configure OG_COMPUTE_PRIVATE_KEY on the server to route through a TEE-attested 0G Compute provider."
          : "Verdict generated by a TEE-attested 0G Compute provider. The provider's signed response is verifiable against its on-chain attestation report."}
      </p>
    </section>
  );
}
